name: 'Swift Android Test'
description: 'Cross-compiles a swift package for Android and runs the test cases in an Android emulator'
inputs:
  swift-version:
    description: 'The version of the Swift toolchain to use'
    required: true
    default: '5.10.1'
  package-path:
    description: 'The folder where the swift package is checked out'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Install Toolchain
      run: brew install swift-android-sdk/toolchain/swift-android-sdk@${{ inputs.swift-version }} skiptools/skip/skip
      shell: bash
    - name: Build package
      run: skip android build --build-tests --package-path ${{ inputs.package-path }}
      shell: bash
        

