name: 'Swift Android Test'
description: 'Cross-compiles a swift package for Android and runs the test cases in an Android emulator'
inputs:
  swift-version:
    description: 'The version of the Swift toolchain to use'
    required: true
    default: '5.10.1'
  package-path:
    description: 'The folder where the swift package is checked out'
    required: true
    default: '.'
  swift-build-flags:
    description: 'Additional flags to pass to the swift build command'
    required: false
    default: ''
  inputs.android-emulator-options:
    description: 'Additional options to pass to the Android emulator'
    required: false
    default: ''
  run-tests:
    description: 'Whether to run the tests or just the build'
    required: true
    default: 'true'
  android-api-level:
    description: 'The API level of the Android emulator to run against'
    required: true
    default: 24
runs:
  using: "composite"
  steps:
    - name: Cache Homebrew packages
      uses: actions/cache@v4
      with:
        path: ~/Library/Caches/Homebrew
        key: homebrew-packages
    - name: Install Toolchain
      run: brew install skiptools/skip/skip swift-android-sdk/toolchain/swift-android-sdk@${{ inputs.swift-version }}
      shell: bash
    - name: Build Swift package for Android
      run: skip android build --build-tests --package-path ${{ inputs.package-path }} ${{ inputs.swift-build-flags }}
      shell: bash
    - name: Run Swift tests on Android emulator
      if: ${{ inputs.run-tests == 'true' }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        emulator-options: ${{ inputs.android-emulator-options }}
        arch: x86_64
        script: |
          skip android test --package-path ${{ inputs.package-path }} ${{ inputs.swift-build-flags }}

